#!/Library/Frameworks/Python.framework/Versions/3.10/bin/python3
import argparse
from folder_creation import main

if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Create folder structure for CMake with CppUTest"
    )
    parser.add_argument("name", type=str, help="the name of your project")
    parser.add_argument(
        "folder",
        type=str,
        default=".",
        help="the location in which to create your project",
    )
    parser.add_argument(
        '-o', '--overwrite', help='overwrite if project already exists', action='store_true'
    )
    main(parser.parse_args())

